from typing import Dict, Tuple, Optional
from pathlib import Path

def is_valid_file(file_path: Path) -> bool: ...
def parse_doc(file_path: Path) -> Dict[str,str]: ...
def query_parameter(parsed_index: Dict[str,str], query: str) -> Optional[str]: ...
def format_output(metadata:str) -> str: ...
def filter_required_params(parsed_index: Dict[str,str]) -> Tuple[str, ...]: ...
def update_doc(content: Dict[str,str], file_path: Path) -> Dict[str,str]: ...

if __name__ == "__main__":
    # print("Hello World!")